### ISSUE TITLE
Opensource dependency checklist

### ISSUE THREAD

**Issue by ckadner** [jupyter-incubator/enterprise_gateway#39]
We currently rely on various 3rd-party libraries and packages which were forked off of open-source projects and modified for our needs without contributing the changes back to the respective upstream repositories.

This issue serves as a checklist of sorts to track progress on getting our open-source dependency house back in order. Individual "sub-tasks" should be linked into this list.

- [x] **[Yarn-Client](https://github.com/toidi/hadoop-yarn-api-python-client):** HTTPS support from [here](https://github.com/lresende/yarn-client/commit/870b65985375800b106ee00e477156d4479cf674) (**Note:** Version 0.2.3 has been deemed sufficient.)
- [x] **[Apache Toree](https://github.com/apache/incubator-toree):** need a SNAPSHOT or release with fixes since [`0.2.0-dev1`](https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0/snapshots/dev1/toree-pip/toree-0.2.0.dev1.tar.gz), i.e. [ASM jar shading](https://github.com/apache/incubator-toree/commit/14c80857a5f2a816cf0405624a32210018e85d53), support [Yarn Cluster mode](https://issues.apache.org/jira/browse/TOREE-369)   --> **Issue #40**
  - [x] update Toree's Python dependencies ... `jupyter_client<5.0,>=4.0` should be `>=4.0` since it works with jupyter_client=5.1
  - [x] Toree builds after June 7, 2017 won't work in Yarn Cluster mode (Toree Main application get stuck in `ACCEPTED` state and will [time out](https://github.com/apache/spark/blob/3d4d11a80fe8953d48d8bfac2ce112e37d38dc90/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/ApplicationMaster.scala#L402) without a `SparkContext` being utilized after `spark.yarn.am.waitTime`, default of 100 seconds) -- see: Toree commit [5cfbc83](https://github.com/apache/incubator-toree/commit/5cfbc83322c290e84f0cc0848c4eba41508ac54d) (_TOREE-390: Lazily initialize spark sessions_)
- [x] **[NB2KG](https://github.com/jupyter/kernel_gateway_demos/tree/master/nb2kg):** variables for request timeouts and user authentication mentioned [here](https://github.com/SparkTC/elyra/issues/23#issuecomment-310223272)
- [x] **[NB2KG docker image](https://hub.docker.com/r/biginsights/jupyter-nb-nb2kg):** need to rebuild and host under *neutral* name on Dockerhub - see [elyra/NB2KG](https://hub.docker.com/r/elyra/nb2kg/)
- [x] **[Notebook](https://github.com/jupyter/notebook/releases):** [Kernel culling](https://github.com/jupyter/notebook/pull/2215) will first appear in the [5.1.0 release](https://github.com/jupyter/notebook/releases/tag/5.1.0) of [Jupyter Notebook](https://github.com/jupyter/notebook/releases/) which is now available.
- [ ] ...

**Comment by kevin-bates** [comment]
Checked off NB2KG docker image since we now have [elyra/NB2KG](https://hub.docker.com/r/elyra/nb2kg/).

@ckadner, @sxguo - can this be closed?

**Comment by ckadner** [comment]
Great. Thank you @kevin-bates!
